bernardosulzbach/dungeon

- checkstyle-for-java-6.xml
- checkstyle.xml
- pom.xml
> sortImportsInGroupAlphabetically for Java 7 or newer

- appveyor.yml
> Appveyor should test with more Java versions.

- README.md
- pom.xml
- src/main/java/org/mafagafogigante/dungeon/achievements/Achievement.java
- src/main/java/org/mafagafogigante/dungeon/achievements/AchievementTracker.java
- src/main/java/org/mafagafogigante/dungeon/achievements/BattleComponent.java
- src/main/java/org/mafagafogigante/dungeon/achievements/ExplorationComponent.java
- src/main/java/org/mafagafogigante/dungeon/commands/CommandSets.java
- src/main/java/org/mafagafogigante/dungeon/date/Date.java
- src/main/java/org/mafagafogigante/dungeon/entity/creatures/CreatureFactory.java
- src/main/java/org/mafagafogigante/dungeon/entity/creatures/DateOfBirthGenerator.java
- src/main/java/org/mafagafogigante/dungeon/entity/creatures/Hero.java
- src/main/java/org/mafagafogigante/dungeon/entity/items/ItemFactory.java
- src/main/java/org/mafagafogigante/dungeon/game/GameState.java
- src/main/java/org/mafagafogigante/dungeon/gui/GameWindow.java
- src/main/java/org/mafagafogigante/dungeon/io/Loader.java
- src/main/java/org/mafagafogigante/dungeon/io/SavesTableWriter.java
- src/main/java/org/mafagafogigante/dungeon/logging/DungeonLogger.java
- src/main/java/org/mafagafogigante/dungeon/stats/Statistics.java
- src/test/java/org/mafagafogigante/dungeon/entity/creatures/DateOfBirthGeneratorTest.java
> Merging all Coverity bugs fixes.

- src/main/java/org/mafagafogigante/dungeon/entity/creatures/Hero.java
- src/main/java/org/mafagafogigante/dungeon/entity/creatures/Observer.java
- src/main/java/org/mafagafogigante/dungeon/spells/SpellData.java
> Removed duplicate code from Hero

- .gitignore
- wiki/wiki.py
> Wiki automation

- wiki/wiki.py
> Wiki script should have a license note

- CONTRIBUTING.md
> CONTRIBUTING should help with environment setup

- README.md
> README should describe the beginning of the game

- pom.xml
Implemented item uniqueness
Closes #231
> Release v5.0.0.

- pom.xml
- src/main/java/org/mafagafogigante/dungeon/io/Loader.java
Throwing exceptions as it should.
> Should log saving and loading exceptions

- src/main/resources/items.json
- src/main/resources/locations.json
> Created another unique item: Red Onyx Watch

- src/main/java/org/mafagafogigante/dungeon/game/ExpandableIntegerSet.java
- src/main/java/org/mafagafogigante/dungeon/game/LocationPresetStore.java
- src/main/java/org/mafagafogigante/dungeon/game/Random.java
- src/main/java/org/mafagafogigante/dungeon/game/Spawner.java
- src/main/java/org/mafagafogigante/dungeon/game/SpawnerPreset.java
- src/main/resources/locations.json
- src/test/java/org/mafagafogigante/dungeon/game/ExpandableIntegerSetTest.java
- src/test/java/org/mafagafogigante/dungeon/game/RandomTest.java
- src/test/java/org/mafagafogigante/dungeon/game/SpawnerPresetTest.java
Updated the related resources
Random now provides a nextInteger with a lower bound too
Wrote tests for ExpandableIntegerSet and SpawnerPreset
Closes #106
> Spawners should use a range for maximum population

- appveyor.yml
> Should use AppVeyor Maven installation

- src/test/java/org/mafagafogigante/dungeon/io/ResourcesFolderTest.java
This will happen if there are no resource files.
> Should check for null array before Arrays.asList()

- src/main/java/org/mafagafogigante/dungeon/commands/CommandLimits.java
- src/main/java/org/mafagafogigante/dungeon/commands/CommandSet.java
- src/main/java/org/mafagafogigante/dungeon/commands/IssuedCommandEvaluation.java
- src/main/java/org/mafagafogigante/dungeon/commands/StringDistanceMetrics.java
- src/test/java/org/mafagafogigante/dungeon/commands/StringDistanceMetricsTest.java
- src/test/java/org/mafagafogigante/dungeon/io/ResourcesFolderTest.java
Even though the algorithm used seem O(n + m), I would rather play it safe in case we ever use an O(nm) solution.
> Should have a safety wrapper around Levenshtein Distance

- checkstyle.xml
- pom.xml
- src/test/java/org/mafagafogigante/dungeon/achievements/AchievementStoreFactoryTest.java
- src/test/java/org/mafagafogigante/dungeon/achievements/AchievementStoreTest.java
- src/test/java/org/mafagafogigante/dungeon/achievements/AchievementTest.java
- src/test/java/org/mafagafogigante/dungeon/achievements/AchievementTrackerTest.java
- src/test/java/org/mafagafogigante/dungeon/date/DungeonTimeParserTest.java
- src/test/java/org/mafagafogigante/dungeon/entity/items/UniquenessRestrictionsTest.java
- src/test/java/org/mafagafogigante/dungeon/io/ResourcesFolderTest.java
- src/test/java/org/mafagafogigante/dungeon/util/CircularListTest.java
- src/test/java/org/mafagafogigante/dungeon/util/DungeonMathTest.java
- src/test/java/org/mafagafogigante/dungeon/world/TimeVisibilityCriterionTest.java
- src/test/java/org/mafagafogigante/dungeon/world/WeatherConditionVisibilityCriterionTest.java
The Maven configuration has already been fixed. Now I only have to fix all the violations I just found out about.
Closes #297
> Should run Checkstyle on the tests too

- src/main/resources/wiki.json
> Fixed two small issues with Sleep on the Wiki

- pom.xml
- src/main/resources/wiki.json
> Release v6.1.0

- src/main/java/org/mafagafogigante/dungeon/entity/Weight.java
- src/test/java/org/mafagafogigante/dungeon/entity/WeightTest.java
This is a step towards increasing the coverage of the entity package.
> Wrote tests for the Weight class

- src/main/java/org/mafagafogigante/dungeon/gui/GameWindow.java
This is done via reflection by setting awtAppClassName.
Closes #307
> Should set application title on Gnome

- pom.xml
- src/main/java/org/mafagafogigante/dungeon/entity/items/ItemFactory.java
> Fixes a BC issue caused in the ItemFactory

- pom.xml
- src/main/java/org/mafagafogigante/dungeon/gui/GameWindow.java
- src/main/java/org/mafagafogigante/dungeon/io/JsonObjectFactory.java
This is a bug fix that will make it into v6.1.2.
> Should close JSON InputStreams (#312)

- src/main/java/org/mafagafogigante/dungeon/schema/rules/FixedArrayJsonRule.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/JsonRuleFactory.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/VariableArrayJsonRule.java
- src/test/java/org/mafagafogigante/dungeon/schema/rules/FixedArrayJsonRuleTest.java
- src/test/java/org/mafagafogigante/dungeon/schema/rules/VariableArrayJsonRuleTest.java
> Should have more specific JSON array rules

- src/main/java/org/mafagafogigante/dungeon/commands/Command.java
- src/main/java/org/mafagafogigante/dungeon/commands/CommandSet.java
- src/main/java/org/mafagafogigante/dungeon/entity/creatures/Hero.java
- src/main/java/org/mafagafogigante/dungeon/game/World.java
- src/main/java/org/mafagafogigante/dungeon/world/Sky.java
- src/main/java/org/mafagafogigante/dungeon/world/SkyFactory.java
- src/main/java/org/mafagafogigante/dungeon/world/TimeVisibilityCriterion.java
- src/test/java/org/mafagafogigante/dungeon/commands/CommandSetTest.java
- src/test/java/org/mafagafogigante/dungeon/world/TimeVisibilityCriterionTest.java
Also fixed issues with TimeVisibilityCriterion.
> Wrote the two Darrowmere Moons

- src/main/java/org/mafagafogigante/dungeon/io/Loader.java
> Should buffer the FIS and FOS in the Loader

- src/main/java/org/mafagafogigante/dungeon/schema/rules/GroupJsonRule.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/IdJsonRule.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/JsonRuleFactory.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/PeriodJsonRule.java
- src/test/java/org/mafagafogigante/dungeon/io/AchievementsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/CreaturesJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/DreamsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/HintsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/ItemsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/LocationsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/PoemsJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/PrefaceJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/ResourcesTypeTest.java
- src/test/java/org/mafagafogigante/dungeon/io/TutorialJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/io/WikiJsonFileTest.java
- src/test/java/org/mafagafogigante/dungeon/schema/rules/GroupJsonRuleTest.java
- src/test/java/org/mafagafogigante/dungeon/schema/rules/IdJsonRuleTest.java
- src/test/java/org/mafagafogigante/dungeon/schema/rules/PeriodJsonRuleTest.java
With a huge amount of code contributed by @UnknownNPC it was possible to get to full JSON schema coverage.
Closes #172
> Complete PR for the JSON tests

- src/main/java/org/mafagafogigante/dungeon/schema/rules/ObjectJsonRule.java
- src/main/resources/creatures.json
- src/test/java/org/mafagafogigante/dungeon/io/ItemsJsonFileTest.java
A small set of fixes that make an impact on gameplay.
> Fixes to JSON resources bug found by tests

- pom.xml
- src/main/java/org/mafagafogigante/dungeon/world/Sky.java
- src/main/resources/wiki.json
Some final adjustments for the last minor release of this series.
> Last adjustments for the v6.2.0 release

- src/main/java/org/mafagafogigante/dungeon/gui/GameWindow.java
- src/main/java/org/mafagafogigante/dungeon/schema/rules/EnumJsonRule.java
These were all reported by Coverity scan.
Closed #377
> Should prevent Null Pointer Exceptions

- README.md
> Should mention YourKit on the README

- README.md
> Should link to Yegor, but present the image

- .travis.yml
- pom.xml
This is the new name of the tool.
> Should use SpotBugs rather than FindBugs

- scripts/check-hash-sum.sh
- scripts/create-hash-sum.sh
- scripts/include.sh
Documented in the include.sh file itself.
> Adds important options to the Bash scripts
